### PR TITLE
make sure DescriptorImage compiled only once

### PR DESCRIPTION
**Pull request by shenqiuyao**
# Pull Request Template

## Description

make sure DescriptorImage compiled only once.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by robertosfield** [comment]
@shenqiuyao apologies for not merging so far.  

The fix itself looks sensible enough, the only reason why I'm holding off from merging is that I have the BufferInfo branch which refactors how BufferInfo and ImageInfo are managed in the scene graph and this work touches on the bug fix you've applied.  This branch doesn't yet address the bug that you've fixed, but will likely change how the required fix will be expressed.

I've been very busy with a number of ongoing tasks so haven't had a chance to complete the BufferInfo refactor, but would like to get back to into in the next two weeks.  It may make sense just to merge your PR as an interim fix if I can't tackle BufferInfo changes  this week.

**Comment by robertosfield** [comment]
Sorry for the delay testing this PR.  I pulled the PR into a shenqiuyao-master branch and tested it and found it crashed, what it looks like is the vk_buffer<int> _bCompiled container is not being initialized to zero so can lead to DescriptorImage's not being compiled at all.  I can only guess that this PR was tested and was just lucky that the memory happened to be initialized to zero.

Give this bug I'm going to close this PR.  I'll leave the shenqiuyao-master checked in, and use this as a reminder of what area needs more work to resolve the problem that this PR is meant to address.  Once I've fixed the underlying problem I'll need some testing from the community.  I should get a fix checked in within the next 4 days.

**Comment by robertosfield** [comment]
@shenqiuyao I have come up with a fix for the multiple redundent copies and checked this into VSG master.  Could you please test it without your application/data?  

eecd2b6271005cefc666738ea575763f64b6d6d7

**Comment by shenqiuyao** [comment]
@robertosfield  ok, I tested it with my data,  it's ok now, consume about 3G memory.

**Pull request closed without merging**
