### PR TITLE
Force cmake version ci

### PR DESCRIPTION
**Pull request by sbrkopac**
## Description

Changed CI to force the installation of the cmake version that VSG uses.

Supports #364 

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Ran CI

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by robertosfield** [comment]
What I have decided to do is merge this draft as a [force-cmake-version-ci](https://github.com/vsg-dev/VulkanSceneGraph/tree/force-cmake-version-ci) branch and have updated the Cmake version to 3.10.x and have merged the [CMake_JOIN_fix](https://github.com/vsg-dev/VulkanSceneGraph/tree/CMake_JOIN_fix) changes. 

I will attempt to aim to get 3.10.x compiling cleanly then step back to see how low we can easily go.

**Comment by robertosfield** [comment]
OK, merging my fix to get things working under 18.04 Linux is now fixed, but Windows doesn't compile, reporting:

Run cmake . -G "Visual Studio 16 2019" -A x64
CMake Error: Could not create named generator Visual Studio 16 2019

Generators
  Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 11 2012 [arch] = Generates Visual Studio 2012 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 10 2010 [arch] = Generates Visual Studio 2010 project files.
                                 Optional [arch] can be "Win64" or "IA64".
  Visual Studio 9 2008 [arch]  = Generates Visual Studio 2008 project files.
                                 Optional [arch] can be "Win64" or "IA64".
  Visual Studio 8 2005 [arch]  = Deprecated.  Generates Visual Studio 2005

**Comment by robertosfield** [comment]
Changing the cmake . -G ... entry to address the Windows build failure with cmake-3.10.x I now get a bit further but hit upon what I presume is a path issue.  I don't know anything about VisualStudio so don't know what changes to attempt next, so will need others with knowledge to pitch in.

Run cmake . -G "Visual Studio 15 2017 Win64"
CMake Error at CMakeLists.txt:3 (project):
  Failed to run MSBuild command:
-- Configuring incomplete, errors occurred!
See also "D:/a/VulkanSceneGraph/VulkanSceneGraph/CMakeFiles/CMakeOutput.log".

    MSBuild.exe

  to get the value of VCTargetsPath:

    The system cannot find the file specified

**Comment by sbrkopac** [comment]
[Visual Studio 15 2017](https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2015%202017.html) is only supported on CMake 3.11+.

[Visual Studio 14 2015](https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2014%202015.html) is supported CMake 3.1+.

**Comment by sbrkopac** [comment]
@robertosfield Looks like Visual Studio 17 isn't supported on the windows-latest image for github so we'd have to go to windows-2016.

**Comment by robertosfield** [comment]
Thanks for the fixes.  

Do you think it's worth merging with master at this point?

**Comment by sbrkopac** [comment]
Yes. I think master should compile and CI cleanly at all times. We should definitely take some learnings away from this situation and continue to iterate on the CI.

**Pull request merged**
