### PR TITLE
Builder position location

### PR DESCRIPTION
**Pull request by rolandhill**
In StateComposer branch:

shaderSet->addAttributeBinding("vsg_position", "VSG_INSTANCE_POSITIONS", 3, VK_FORMAT_R32G32B32_SFLOAT, vsg::vec3Array::create(1));

should be location 4 as below

shaderSet->addAttributeBinding("vsg_position", "VSG_INSTANCE_POSITIONS", 4, VK_FORMAT_R32G32B32_SFLOAT, vsg::vec3Array::create(1));

Test with 
./vsgbuilder --sphere -n 10000 --debug

### CODE REVIEW

**Comment by robertosfield** [comment]
@rolandhill thanks for the fix, it comes along with several others.  Ideally for me each one would be separate,, but I could just manually cherry-pick if you want, just tell me which ones are needed and a bit of explanation of each.

**Comment by rolandhill** [comment]
Hi Robert,

I'm hopeless at PRs. Sorry about that.

It's just a single key stroke, so maybe you can just change it. Go by the last commit only (FIX: Change vsg_position for Phong shader to location 4.)

Regards,
Roland

**Comment by robertosfield** [comment]
I've merge the fix to Builder.cpp.  Do you want me to merge the changes to quat.h and adapt the .gitignore to work on all platforms?

The changes to DatabasePager I remain aware of as a TODO item.  So much stuff for me to get done still to get to the 1.0...

**Comment by robertosfield** [comment]
Just review the changes .gitingore, I see they don't need to be adapted and should be mergeable as is.

**Comment by rolandhill** [comment]
I added some functions to quat.h, but haven't completed the code to test them yet. I'll send a (better) PR once I've checked them if you like. Again, apologies for the poor PR as I know you've got more productive things to do.
Roland

**Pull request closed without merging**
