### PR TITLE
repair the Barrier taking account read accesses

### PR DESCRIPTION
**Pull request by mp3butcher**
following https://github.com/vsg-dev/VulkanSceneGraph/pull/162

## Fixes
https://github.com/vsg-dev/VulkanSceneGraph/issues/160

## Type of change

Mutex instead of condition

### CODE REVIEW

**Comment by mp3butcher** [comment]
invoking the abstract machine, this solution is not good enough but seems not to exhibit same issue

**Comment by mp3butcher** [comment]
oups too drunk

**Comment by mp3butcher** [comment]
not perfect in regards to the Abstract Machine but working

**Comment by robertosfield** [comment]
And efficient latch is designed around a condition variable, just throwing this away is not a solution.

**Comment by mp3butcher** [comment]
your problem is that condition variable is waited after it has been notified...It's obvious in the code you have copy paste from internet

**Comment by mp3butcher** [comment]
the only way current design could be used safely is by launching a waiting thread before the workers

**Comment by robertosfield** [comment]
If there is a usage case that is problem then create a simple test case
that illustrates the problem.  I will then look at it.  If you don't do it
I'll write it myself when I have a clear run at it.

**Comment by mp3butcher** [comment]
test case:
```
mainthread init latch to 1
mainthread lauching 1 worker with latch->count_down-)
mainthread latch.wait
```
for i in `seq 0 2000000`; do  ./a.out 
In some cases worker will have finished before wait and latch wait forever

**Pull request closed without merging**
