### PR TITLE
Add vsgMacros.cmake file

### PR DESCRIPTION
**Pull request by rhabacker**
## Description
see #305 for detailed description

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
The VulkanScenGraph package was created with this patch and installed in a local directory. The vsgExamples package was then created with these files installed and checked to see if vsgMacros.cmake was included.

**Test Configuration**:
* OS  version: openSUSE Leap 15.2
* Toolchain: gcc 10

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by robertosfield** [comment]
I can't see any contents for vsgMacros.cmake yet?  Is this expected?

**Comment by rhabacker** [comment]
For this initial commit, yes.
I added a new macro for the maintainer option, which does not conflict with cmake stuff in the other repos and will only be used by migrating to that macros by a dedicated commit. 

Moving other cmake stuff without a synchronized commit in the other repos may break configuring there and needs some refactoring in front of. That belongs for example to unconditional added cmake targets like the target 'clang-format'.

**Comment by robertosfield** [comment]
On Wed, 25 Aug 2021 at 09:25, Ralf Habacker ***@***.***>
wrote:

> For this initial commit, yes.
> I added a new macro for the maintainer option, which does not conflict
> with cmake stuff in the other repos and will only be used by migrating to
> that macros by a dedicated commit.
>
> Moving other cmake stuff without a synchronized commit in the other repos
> may break configuring there and needs some refactoring in front of. That
> belongs for example to unconditional added cmake targets like the target
> 'clang-format'
>
We should be able to merge with VSG master first then update the other
projects.  Would it be helpful for you to have a VsgMarco branch in all the
related projects for you to work on?

**Comment by rhabacker** [comment]
> Would it be helpful for you to have a VsgMarco branch in all the related projects for you to work on?

The current workflow is to fork a repo into the private name space and to open a merge request, which starts a pipeline on github CI for the VulkanSceneGraph repo. 

Which benefit would a dedicated branch have in the upstream repo compared to the workflow mentioned above ?

I think that having CI support for the other repos would be more helpful to see hidden issues.

**Comment by rhabacker** [comment]
> We should be able to merge with VSG master first then update the other
projects.  

That results into wrapping the related stuff into macros e.g for the `clobber` target the following macro will be added:
```
macro(add_target_clobber)
    add_custom_target(clobber
        COMMAND git clean -d -f -x
    )
endmacro()
```
which can be used  in any other repo by adding  `add_target_clobber()` in that top level CMakeLists.txt

Or when arguments are required as for the `docs` target  the following stuff can be used:

```
add_target_docs(
    FILES
        ${CMAKE_SOURCE_DIR}/include
)
```
or 
```
add_target_clang_format(
    FILES
        ${CMAKE_SOURCE_DIR}/include/*/*.h
        ${CMAKE_SOURCE_DIR}/src/*/*.h
        ${CMAKE_SOURCE_DIR}/src/*/*.cpp
        ${CMAKE_SOURCE_DIR}/applications/*/*.h
        ${CMAKE_SOURCE_DIR}/applications/*/*.cpp
    EXCLUDES
        ${CMAKE_SOURCE_DIR}/src/stbi/stb_image.h
        ${CMAKE_SOURCE_DIR}/src/dds/tinyddsloader.h
)
```

As those macros are also used in the VulkanSceneGraph build system, they can be verified within this pr.

**Comment by rhabacker** [comment]
> COMMAND git clean -d -f -x
        
This needs to be extended to 
```
COMMAND git -C ${CMAKE_SOURCE_DIR} clean -d -f -x
```
to enter the source dir first.

**Comment by robertosfield** [comment]
I have gone ahead and created a VSG vsgMacros.cmake branch and merged your work into this, as I've done for vsgXchange.  I'll next create vsgMacros.cmake branches for vsgGIS, vsgImGui.  

vsgUnity and vsgFramework might also be candidates but they both are a bit non standard so I'll leave these.

I'll now close this PR and the work is already merged as the vsgMacros.cmake branch.  Merging this work doesn't mean I've review it though, I'll do this at a later date when I have time to sit down and do proper review and testing.  I'm merging as a branch to help get the ball rolling in a way that doesn't impact the respective masters.

**Comment by rhabacker** [comment]
>  I'll next create vsgMacros.cmake branches for vsgGIS, vsgImGui.
The vsgExamples repo is also a candidate.

**Pull request closed without merging**
