### PR TITLE
Azure pipelines

### PR DESCRIPTION
**Pull request by fcami**
# Add support for Azure pipelines

## Description

Add support for Azure Pipelines CI

- add two build definitions: Ubuntu, and Ubuntu+Windows+macOS
- add symlink to switch between Ubuntu and multi-platform builds

This requires:
- setting up the Azure part as detailed in the official documentation:
https://learn.microsoft.com/en-us/azure/devops/pipelines/get-started/pipelines-sign-up?view=azure-devops#signup-github
- creating a pipeline using the VSG's GitHub repository
- Select "Existing Azure Pipelines YAML file" once this PR is merged
- The path to the YAML file is exactly: azure-pipelines.yml

## Type of change

- [X] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by fcami** [comment]
Closing, this won't be necessary. Cool!

**Comment by robertosfield** [comment]
I'm not familiar with Azure.

Could you explain the motivation and benefits of this?

**Comment by fcami** [comment]
I noticed Azure was building this project so I closed the PR. I've reopened it for discussion.
The main motivation is to answer the question "is VSG buildable on all platforms".

**Comment by robertosfield** [comment]
We already have automated builds running.  I don't know what going through Azure adds to the mix.  Details of existing builds can be found in .guthub/workflows/ci.yml:

    https://github.com/vsg-dev/VulkanSceneGraph/tree/master/.github/workflows

I'm closing this PR as it doesn't appear to have any value add over what we already have working.

**Pull request closed without merging**
