### PR TITLE
Changed ci to use a matrix approach

### PR DESCRIPTION
**Pull request by sbrkopac**
## Description

Cleaned up the continuous integration so its much cleaner and can be easily extended using the matrix.

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by sbrkopac** [comment]
I believe so: 
```
-- The following OPTIONAL packages have been found:

 * vsg_glslang
```
Unless I need to enable it via a cmake flag? I just checked on my local windows machine and I can see that code path being compiled.

**Comment by sbrkopac** [comment]
It looks like the way Khronos is packaging things has evolved a little bit. The macOS DMG is now an installer rather than just packaged files so I've asked for support in the here humbletim/install-vulkan-sdk#3.

@robertosfield What are your thoughts on bumping the minimum requirement to Vulkan Version ```1.2.176.1```? The other option is we could just bump the CI and handle exceptions as they come.

**Comment by robertosfield** [comment]
On Fri, 25 Feb 2022 at 20:22, Sam Brkopac ***@***.***> wrote:

> It looks like the way Khronos is packaging things has evolved a little
> bit. The macOS DMG is now an installer rather than just packaged files so
> I've asked for support in the here humbletim/install-vulkan-sdk#3
> <https://github.com/humbletim/install-vulkan-sdk/issues/3>.
>
> @robertosfield <https://github.com/robertosfield> What are your thoughts
> on bumping the minimum requirement to Vulkan Version 1.2.176.1? The other
> option is we could just bump the CI and handle exceptions as they come.
> Message ID: ***@***.***>

Bump the min requirements for the automated build?  Is it something that
you could just do for macOS is that's causing problems?

**Comment by robertosfield** [comment]
I have little expertise on  CI, the changes look cleaner, but not in a good position to provide a proper technical review so happy to defer to others who've spent more time with it.  @sbrkopac do you feel this work is ready to merge now?

**Comment by sbrkopac** [comment]
Yes, I'm pretty happy with this. This covers all the functionality that we had before. @robertosfield I haven't had a chance to review the [Safety Critical](https://www.khronos.org/news/press/khronos-releases-vulkan-safety-critical-1.0-specification-to-deliver-safety-critical-graphics-compute) update yet. But we can get that in at a later date.

**Pull request merged**
