### PR TITLE
Cmake adjustments

### LINKED ISSUE #318: Master won't build on windows
**Describe the bug**
Looks like 7a4a0a06ad17027294ba4f2e1b0671c3197f9935 broke installation of VSG on windows. Looks like when VSG_MACROS_INSTALLED is enabled then the uninstall.cmake file is skipped from the installation.

**Expected behavior**
VSG should install correctly to the target folders.

**Screenshots**
```
Build started...
1>------ Build started: Project: INSTALL, Configuration: RelWithDebInfo x64 ------
1>-- Install configuration: "RelWithDebInfo"
1>CMake Error at cmake_install.cmake:36 (file):
1>  file INSTALL cannot find
1>  "C:/Programming/libraries/VulkanSceneGraph/build/uninstall.cmake": No
1>  error.
1>
1>
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: The command "setlocal
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: "C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=RelWithDebInfo -P cmake_install.cmake
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmEnd
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmErrorLevel
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: exit /b %1
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :cmDone
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(155,5): error MSB3073: :VCEnd" exited with code 1.
1>Done building project "INSTALL.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 3 up-to-date, 0 skipped ==========
```

**Additional context**

### PR DESCRIPTION
**Pull request by sbrkopac**
## Description

Currently VSG stores templates and macros in the build folder. I've moved them over to a new cmake folder which is the recommended approach to those objects.

Fixes #318 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- [X] Did full rebuild after nuking the build folder

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by robertosfield** [comment]
@rhabacker Could you do a review and provide feedback on the conflicts with your the PR #321 I've just merged from you.  Thanks.

**Comment by rhabacker** [comment]
You need to rebase your branch with VulkanSceneGraph master. 

After that has been performed please squash the following commits into one:

removed files b8125db
moved cmake specific template files and macros to new cmake folder 0c855c8
updated paths to use the new cmake folder 7262146

**Comment by sbrkopac** [comment]
Rebased and squashed the commits.

**Comment by rhabacker** [comment]
The files build/*.txt  are not related to moving the cmake files and breaks some cmake targets (for example https://github.com/vsg-dev/VulkanSceneGraph/blob/4bc646cf3efec548c305d0abdbf0a74cefb0a482/CMakeLists.txt#L71).

Changes for them should be removed from this pr including the first commit.

**Comment by OpenSiege** [comment]
They are not directly related to moving the cmake files, but I don't think it's best practice to have a "build" folder supplied by VSG that the user can't sanitize. I think creating an entirely new scripts folder for those is probably overkill.

@robertosfield thoughts?

**Comment by sbrkopac** [comment]
They are not directly related to moving the cmake files, but I don't think it's best practice to have a "build" folder that the user can't completely sanitize. It also probably overkill to have a scripts folder.

@robertosfield thoughts?

**Comment by rhabacker** [comment]
> I don't think it's best practice to have a "build" folder supplied by VSG that the user can't sanitize.

The use of the "build" folder is a common design pattern in all related vsg. git repos. If changes are desired or required, I think an appropriate ticket should be opened and resolved with additional pull requests.

**Comment by robertosfield** [comment]
I originally put all the build related files into a VulkanSceneGraph/build directory, as not all the files are specifically cmake related, though all are invoked by the build support generated by cmake so perhaps putting things in a cmake subdirectory would be OK. 

I hindsight if users have a preference of creating their own build directories locally in their projects then the fact that the VSG already utilizes that directory name could lead to some confusion/mistakes in just using their habitual working convnetions on the VSG.  So for this reason I can see value in changing the names.

The OSG has has used the CMakeModules name for cmake related files, and a few other directories for other build/packaging related files.  The OSG was a relatively early adopter of cmake so modern conventions may differ from what was originally adopted.  I don't think there is particular value in adopting CMakeModules as a name, but adopting cmake also might not age well - in a decades time will folks prefer another name?

So... using VulkanSceneGraph/cmake is probably better than VulkanSceneGraph/build purely from the standpoint of avoiding some folks making mistakes.  Adopting this will require any of the VSG sibling projects to adopt it as well.  I will need to do a review.  @rhabacker do you foresee any breakages with this PR as it now stands?

**Comment by rhabacker** [comment]
> @rhabacker do you foresee any breakages with this PR as it now stands?

Yes, it will break the cmake targets  `cppcheck` and `build_all_h`

**Comment by robertosfield** [comment]
I have checkout out the PR as a local sbrkopac-cmake-adjustments master branch and fixed the breakage of cppcheck.  

Once I've completed more testing I'll have a think about how it looks.

**Comment by robertosfield** [comment]
@rhabacker  When I run cmake for the first time I've seeing:


-- The following OPTIONAL packages have been found:

 * Vulkan
 * Threads
 * PkgConfig

-- The following REQUIRED packages have been found:

 * vsg_glslang

Which is a bit inverted, Vulkan isn't optional, glslang is.  

Also vsg_glslang cmake cmake support is provided by the VulkanSceneGraph itself, so you don't need to look for it, it's what this vsg_glang script searches for that is optional.

I don't think this oddity is related to this PR, but thought it worth highlighting as an issue that needs to be resolved as follow up.

**Comment by rhabacker** [comment]
>  I fixed the breakage of cppcheck

Please note that build_all_h is also broken, because a text file is referenced inside the associated `build_all_h.cmake` file

**Comment by robertosfield** [comment]
Thanks for the notes, I've merged this PR and fixed the cppcheck and build_all_h paths.

**Pull request merged**
