### PR TITLE
[Last PR substitute] Subpass + Secondary Command Buffer

### PR DESCRIPTION
**Pull request by mp3butcher**
a cleaner substitute of my last pr
#139
mergeable when rolledback

### CODE REVIEW

**Comment by vsg-dev** [comment]
I am surprised by the number of conflicts that github has flagged for me to resolve before I can merge. Something odd happen in merging?

**Comment by mp3butcher** [comment]
#139 have to be rollback in order this r to be mergeable with subpass and master

**Comment by vsg-dev** [comment]
Thanks, when I get back to my dev system I'll try the suggest rest.

FYI. I've now merged the multi_gpu branch with master which may well through up lots of conflicts for your own work on subpasses.  Next week I'll put some time aside for reviewing the classes you've written and the usage case and work out how best to bring this functionality into master.  What I'll probably do is create a new branch based on master and pull it bits from subpass and try to come up with a coherent union that gets the functionality into master.  I'll use your vsgsubpass example as a target, and perhaps try my own test programs as well once I get confident in this type of functionality.

**Comment by vsg-dev** [comment]
I just checkout out subpass, updated, then ran the suggested:

  git reset --hard 435380503ca2ed3a00004737ac7e35499d115fd7

This ran without warnings, but I tried pushing and got the warning : 

To https://github.com/vsg-dev/VulkanSceneGraph.git
 ! [rejected]        subpass -> subpass (non-fast-forward)
error: failed to push some refs to 'https://github.com/vsg-dev/VulkanSceneGraph.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

But if I do a pull would I not be back to square one?

**Comment by vsg-dev** [comment]
I have just tried do a manual merged and have started working my way through the reported conflicts and have got to changes that I really don't know how to resolve without breaking things.  I can't safely proceed from here with this PR.

What I'll do is create a new branch and try to pull your new code across or reproduce the functionality in ways I think fit with the rest of the VSG rather than trying to work around this subpass branch.  I will see how far I get.

**Comment by mp3butcher** [comment]
> This ran without warnings, but I tried pushing and got the warning :
> 
> To https://github.com/vsg-dev/VulkanSceneGraph.git
> ! [rejected] subpass -> subpass (non-fast-forward)
> error: failed to push some refs to 'https://github.com/vsg-dev/VulkanSceneGraph.git'
> hint: Updates were rejected because the tip of your current branch is behind
> hint: its remote counterpart. Integrate the remote changes (e.g.
> hint: 'git pull ...') before pushing again.
> hint: See the 'Note about fast-forwards' in 'git push --help' for details.
> 
> But if I do a pull would I not be back to square one?

you have to force the push as history is different:
`git push vsg_dev subpass --force`

**Comment by mp3butcher** [comment]
> > This ran without warnings, but I tried pushing and got the warning :
> > To https://github.com/vsg-dev/VulkanSceneGraph.git
> > ! [rejected] subpass -> subpass (non-fast-forward)
> > error: failed to push some refs to 'https://github.com/vsg-dev/VulkanSceneGraph.git'
> > hint: Updates were rejected because the tip of your current branch is behind
> > hint: its remote counterpart. Integrate the remote changes (e.g.
> > hint: 'git pull ...') before pushing again.
> > hint: See the 'Note about fast-forwards' in 'git push --help' for details.
> > But if I do a pull would I not be back to square one?
> 
> you have to force the push as history is different:
> 
> ```
> git reset --hard 435380503ca2ed3a00004737ac7e35499d115fd7 on vsg-dev/subpass then
> 
> git push vsg-dev subpass --force
> ```

I just clean and clarify the design more likely to be review

**Comment by vsg-dev** [comment]
@mp3butcher I have just merged master into subpass for the VSG and vsgExamples so if you are still working on the respective subpass branches you'll need to pull to get the latest changes.

**Pull request merged**
