### PR TITLE
added a VulkanSceneGraph folder property to clean up IDE layout

### PR DESCRIPTION
**Pull request by sbrkopac**
## Description

Added a folder property to all targets to keep IDE layouts clean. I didn't wrap these in ifdefs for windows as I believe they work for other IDEs as well.

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Regenerated my visual studio solutions.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by robertosfield** [comment]
What would happen for the use of vsgMacros in the sibling projects like vsgGIS, vsgXchange, would these also be put into a VulkanSceneGraph IDE folder?

**Comment by robertosfield** [comment]
@rhabacker could you have a look over this PR.  It modifies the vsgMacros.cmake so will have an impact on the sibling projects, which may or may not be desirable.  I don't have an IDE to see the effects of the PR so easily make a judgement call on it.

**Comment by rhabacker** [comment]
@robertosfield: There is nothing in the cmake doc for the [FOLDER](https://cmake.org/cmake/help/latest/prop_tgt/FOLDER.html#prop_tgt) property that relates to your question. With qtcreator on Linux, which is what I use for development, I see no change when I switch to this branch. 
It would be helpful to get a screenshot of the tree in the IDE for this and a sibling project to get an idea of what is changed by this.

**Comment by sbrkopac** [comment]
@robertosfield yes, that is correct. they'd fall under the VulkanSceneGraph folder.

Here is a before and after snapshot of my IDE:

internal-prior-to-property

internal-after-property

It's not a huge deal but as you start to import more and more projects it gets a little messy.

**Comment by robertosfield** [comment]
Thanks for the screenshots @sbrkopac.  What happens when you work with the sibling projects like vsgGIS, vsgImGui, vsgXchange and vsgExamples?  They now use the vsgMacros.cmake so if I'm reading it correctly would drop under the same VulkanSceneGraph folder.

**Comment by rhabacker** [comment]
> They now use the vsgMacros.cmake so if I'm reading it correctly would drop under the same VulkanSceneGraph folder.

The cmake variable `${PROJECT_NAME}` would help here

**Comment by sbrkopac** [comment]
I had a semi-working example but I'm really struggling to use both ExternalProject and FetchContent. When use either of them, I get some errors.

**Comment by robertosfield** [comment]
On Mon, 27 Sept 2021 at 08:34, Sam Brkopac ***@***.***> wrote:

> I had a semi-working example but I'm really struggling to use both
> ExternalProject and FetchContent. When use either of them, I get some
> errors.
>
> Sam, are you replying to a different topic?  How is this related to the
Folder property?

Do you have any thoughts on Ralf's suggestion of using ${PROJECT_NAME}?

>

**Comment by sbrkopac** [comment]
Sorry, yes - it's related to your question about including other projects such as vsgGIS, vsgExamples, and the other external projects.

The project name is a good idea and I'll see what that looks like in Windows.

I don't have a macOS so I'm flying blind there.

**Comment by robertosfield** [comment]
I have gone ahead and merged this fix.  And then applied @rhabacker  suggestion of using ${PROJECT_NAME} instead of "VulkanSceneGraph" in vsgMacros.cmake.  @sbrkopac  could you test out VSG master and see if this extra commit works fine.

    31f5e2f55f480ae98af8aa36b345e4cb31d609cf

**Pull request merged**
