### PR TITLE
Macos keys

### LINKED ISSUE #689: MacOS Keys vsginput
**Describe the bug**
Running vsginput and pressing the z on the keyboard produces the following screen shot.
Screenshot 2023-01-12 at 4 07 44 PM
which is incorrect.

**To Reproduce**
1) on MacOs run vsginput
2) press the z key
3) the output on the screen produces 'v' which is incorrect.

**Desktop (please complete the following information):**
Darwin ares 22.2.0 Darwin Kernel - Browser [e.g. chrome, safari]

This is likely due to the _keycodeMap in MacOS_Window.mm.
The keys are a mix of ASCII characters and MacOS virtual keys.

### PR DESCRIPTION
**Pull request by kannode**
# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #689, #696

## Type of change

Please delete options that are not relevant.

- [X ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Build vsginput and vsgimgui_example on MacOs and test by pressing the modifier keys.
In vsgimgui_example go to Tools/Metrics and Open up the "input" line to see keystrokes.

**Test Configuration**:
* Hardware: M1 Mac

## Checklist:

- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [X ] My changes generate no new warnings

### CODE REVIEW

**Comment by robertosfield** [comment]
Just done a first pass review, could you make changes without changing coding style of the original code i.e. don't move { to where you prefer.  Changing ancillary code obscures the actual functional changes, and changing coding style from preference to preference is just going to make code incoherent.

**Comment by kannode** [comment]
@robertosfield I just looked at the diffs; yikes, looks like I changed every curly brace during auto format. I assumed the clang-format file took care of it when I formatted the code. I'll take a look again for future commits.

**Comment by robertosfield** [comment]
I periodically run clang-format to clean up formatting of source code, it isn't run automatically.  In the case of the .mm files, these are cpp files so clang-format cried foul when I attempted to add it in the list of files to run it on.

**Comment by robertosfield** [comment]
I have created a macos_key_fixes branch that attempts to cherry pick the relevant changes from the macos-keys PR while avoiding the rest of the irrelevant changes in coding style that littered the original PR.   

https://github.com/vsg-dev/VulkanSceneGraph/tree/macos_key_fixes

I may have made mistakes in this as it's was a manual operation to try and spot the relevant vs misleading changes and then pull them across in what I'm hoping is an appropriate way.  

I am really uncomfortable doing this type of repair work on PR's as it's so error prone and so much extra work.  For future PRs I think it would be best to just reject them as I'm not the best person to judge what is relevant change or not.

For this PR, @kannode  could you check out the macos_key_fixes branch and see if it builds and works fine.  If it does I'll close this PR and create an new one for the clean up branch and get them merged with VSG master. Thanks.

**Comment by kannode** [comment]
- Thank you for doing the painful edit. Feel free to tell me to go ahead and do the repair work.- 
-  Just tested macos_key_fixes. It works.
- The code changes are correct.

**Comment by robertosfield** [comment]
Thanks for testing.  I've gone ahead and merged the macos_key_fixes branch so can now close this PR.

**Pull request closed without merging**
