### PR TITLE
Reverse depth

### PR DESCRIPTION
**Pull request by timoore**
# Pull Request Template

## Description

Implement the reverse depth buffer scheme, as discussed on the mailing list.

## Type of change

- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

## How Has This Been Tested?

Ran various examples

### CODE REVIEW

**Comment by robertosfield** [comment]
Wow. Is that the only changes that are required?

**Comment by timoore** [comment]
On Fri, Jan 7, 2022 at 6:27 PM Robert Osfield ***@***.***>
wrote:

> Wow. Is that the only changes that are required?
>
> Yes. To benefit from the scheme you need to specify a floating point depth
buffer. I can create a branch in vsgExamples if you want,  but it's pretty
basic:
        windowTraits->depthFormat = VK_FORMAT_D32_SFLOAT;

Tim

**Comment by robertosfield** [comment]
HI Tim,

On Fri, 7 Jan 2022 at 17:43, timoore ***@***.***> wrote:

> > Wow. Is that the only changes that are required?
> >
> > Yes. To benefit from the scheme you need to specify a floating point
> depth
> buffer. I can create a branch in vsgExamples if you want, but it's pretty
> basic:
> windowTraits->depthFormat = VK_FORMAT_D32_SFLOAT;


Do know the status of support for VK_FORMAT_D32_SFLOAT across desktop and
embedded platforms?  If some platforms don't efficiently support it then we
may need to be careful about choosing it.

**Comment by timoore** [comment]
I'll do some research, but I wouldn't propose making it the default;
applications that need the depth precision can use a floating point depth
buffer. With a traditional fixed point depth buffer reverse Z doesn't help,
but it doesn't hurt either.

**Comment by robertosfield** [comment]
Hi @timoore,  I have merged this PR as #timoore-reverse-depth, this will allow testing and updating of any examples that we need to update.

**Comment by robertosfield** [comment]
@timoore I've merged master into the timoore-reverse-depth branch and added the following comments, do these look appropriate?

diff --git a/include/vsg/maths/transform.h b/include/vsg/maths/transform.h
index 8ecf73d5..404d417a 100644
--- a/include/vsg/maths/transform.h
+++ b/include/vsg/maths/transform.h
@@ -145,6 +145,9 @@ namespace vsg
     }
 
     // Reverse depth convention: 1 to 0 depth range. Y NDC coordinates are inverted in Vulkan.
+    // For best precision we record setting up Windows with windowTraits->depthFormat = VK_FORMAT_D32_SFLOAT;
+    // Background reading : https://developer.nvidia.com/content/depth-precision-visualized
+    //                      https://vincent-p.github.io/posts/vulkan_perspective_matrix/
     template<typename T>
     constexpr t_mat4<T> perspective(T fovy_radians, T aspectRatio, T zNear, T zFar)
     {
@@ -156,6 +159,7 @@ namespace vsg
                          0, 0, (zFar * zNear) * r, 0);
     }
 
+    // Reverse depth convention: 1 to 0 depth range. Y NDC coordinates are inverted in Vulkan.
     template<typename T>
     constexpr t_mat4<T> perspective(T left, T right, T bottom, T top, T zNear, T zFar)
     {

I also created a timoore-reverse-depth branch of vsgExamples to update the models and examples. So far I've only updated the models.  The changes are:

    [timoore-reverse-depth](https://github.com/vsg-dev/vsgExamples/compare/timoore-reverse-depth)

I will also bump the VSG version before I go ahead and merge with master.

Let me know any issues/tasks left to do with this work.

**Comment by robertosfield** [comment]
I have now finished the updates to [vsgExamples timoore-reverse-depth](https://github.com/vsg-dev/vsgExamples/compare/timoore-reverse-depth)

**Comment by robertosfield** [comment]
I've spotted a regression in vsginersection - it looks like it's mapping of mouse coords into world coords is broken by the reverse depth.  We may need to detect when reverse depth is being used.  @timoore Any thoughts?

**Comment by timoore** [comment]
I'll take a look.
Tim

**Comment by robertosfield** [comment]
The vsgintersection example should report intersections but with the reverse depth changes fails to do so.  It looks like the LineSegmentIntersector constructor that takes window coords is failing to correctly map to line segment in world coords.

**Comment by timoore** [comment]
Yeah, taking a look at that code right now. I think it was following OpenGL
depth conventions before. I can make a fix this evening if you don't get to
it first.

Tim

**Comment by robertosfield** [comment]
@timoore no need to look into the issue.  I have a preliminary fix.  I need to do more testing before I merge any changes.  Ideally I'd like the LineSegmentIntersector to be able to work with both conventional depth order and reverse depth order.  This will require a check against the projection matrix.  I'll figure out what this needs to be tomorrow.

**Comment by timoore** [comment]
I have this fix for the reverse depth case:

modified   src/vsg/traversals/LineSegmentIntersector.cpp
@@ -148,8 +148,8 @@ LineSegmentIntersector::LineSegmentIntersector(const
Camera& camera, int32_t x,
         ndc.set((static_cast<float>(x) - viewport.x) / viewport.width,
(static_cast<float>(y) - viewport.y) / viewport.height);
     }

-    vsg::dvec3 ndc_near(ndc.x * 2.0 - 1.0, ndc.y * 2.0 - 1.0,
viewport.minDepth * 2.0 - 1.0);
-    vsg::dvec3 ndc_far(ndc.x * 2.0 - 1.0, ndc.y * 2.0 - 1.0,
viewport.maxDepth * 2.0 - 1.0);
+    vsg::dvec3 ndc_near(ndc.x * 2.0 - 1.0, ndc.y * 2.0 - 1.0,
viewport.maxDepth);
+    vsg::dvec3 ndc_far(ndc.x * 2.0 - 1.0, ndc.y * 2.0 - 1.0,
viewport.minDepth);

     auto projectionMatrix = camera.projectionMatrix->transform();
     auto viewMatrix = camera.viewMatrix->transform();

**Comment by robertosfield** [comment]
That's similar to the changes I've made.  I've got code that toggles for reverse depth and conventional, this is what my experimental code looks like:

+    bool reverse_depth = false;  
+
     vsg::dvec3 ndc_near(ndc.x * 2.0 - 1.0, ndc.y * 2.0 - 1.0, viewport.minDepth * 2.0 - 1.0);
     vsg::dvec3 ndc_far(ndc.x * 2.0 - 1.0, ndc.y * 2.0 - 1.0, viewport.maxDepth * 2.0 - 1.0);
+    vsg::dvec3 ndc_new_near(ndc.x * 2.0 - 1.0, ndc.y * 2.0 - 1.0, reverse_depth ? viewport.maxDepth : viewport.minDepth);
+    vsg::dvec3 ndc_new_far(ndc.x * 2.0 - 1.0, ndc.y * 2.0 - 1.0, reverse_depth ? viewport.minDepth : viewport.maxDepth);

**Comment by robertosfield** [comment]
I have checked in a fix that works on both reverse_depth and conventional projection matrices. #4f29796863e78845cb522ab93970ef36a459ef9b

I will do some more testing this morning, all going well will merge the reverse depth with VSG master and vsgExamples.  There is potential issues for existing users though, I'll post info to vsg-users to raise the profile of the issues they may see.

**Comment by robertosfield** [comment]
All the changes are now merged with VSG master.

**Pull request merged**
