### PR TITLE
Bump ci vulkan sdk

### PR DESCRIPTION
**Pull request by AnyOldName3**
Fixes CI for forks by:
* Switching to a version of the Vulkan SDK that's still available.
* Switching to a version (which hasn't made it to a release yet) of `install-vulkan-sdk` that can handle slightly newer Vulkan SDK packages.

It doesn't switch to the latest release as no version of `install-vulkan-sdk` can deal with it yet.

### CODE REVIEW

**Comment by robertosfield** [comment]
I have merged this PR as a branch and will see what happens with the automated build:

https://github.com/vsg-dev/VulkanSceneGraph/tree/AnyOldName3-bump-ci-vulkan-sdk

**Comment by robertosfield** [comment]
@AnyOldName3 automated build has run cleanly, is there any more testing we need to do before I merged with VSG master?

**Comment by AnyOldName3** [comment]
It's not exactly more testing, as it's already happened, but here's a CI run on my fork from the gamma correctness branch which failed due to not having these commits https://github.com/AnyOldName3/VulkanSceneGraph/actions/runs/11332586516/job/31515009697 and one from this branch that now works https://github.com/AnyOldName3/VulkanSceneGraph/actions/runs/11350773480/job/31569912536

**Comment by robertosfield** [comment]
So go ahead and merge with VSG master?

**Comment by AnyOldName3** [comment]
Yeah, I think it's ready.

**Pull request merged**
