### PR TITLE
Added windows-2019 as windows-latest is now windows-2022

### PR DESCRIPTION
**Pull request by sbrkopac**
# Pull Request Template

## Description

Added windows-2019 as windows-latest is now windows 2022.

Fixes # (issue)

https://groups.google.com/g/vsg-users/c/_Fb3IojRmaA/

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Ran CI

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by vsg-dev** [comment]
What version does Window-latest work on typically?  Is vs2022 newer than latest?  So Windows-latest is Windows-not-quite-latest?

**Comment by sbrkopac** [comment]
Thats

> What version does Window-latest work on typically? Is vs2022 newer than latest? So Windows-latest is Windows-not-quite-latest?

I was a bit hasty on this. Looks like windows-2022 became latest 4 days ago! I will adjust the PR to reflect windows 2019 and windows-latest.

**Comment by sbrkopac** [comment]
This looks correct now.

**Comment by robertosfield** [comment]
Is VS2019 likely to produce different errors to VS2022? If VS2022 is stricter then it should be safe to just build against VS2022.

The builds aren't free of energy demand and CO2, so I'd rather keep things down to builds that are really unique.  Potentially as we approach big releases then building on a wider set of platforms would be appropriate/  Perhaps stable branches should have a wider set of builds and dev ones just stick to the main ones.

**Comment by sbrkopac** [comment]
Hey Robert,

After giving this some thought, I agree with you. We could make the big matrix build a manual build step or potentially only run it on master. I'll give this some thought this week and see what I can come up with.

**Comment by robertosfield** [comment]
On Wed, 30 Mar 2022 at 17:54, Sam Brkopac ***@***.***> wrote:

> After giving this some thought, I agree with you. We could make the big
> matrix build a manual build step or potentially only run it on master. I'll
> give this some thought this week and see what I can come up with.
>
> I'm open to suggestions.  Main main priority is the code and shaking that
down.  The automated builds help but as with all things the law of
diminishing returns applies - as long as the main platforms are covered and
catch the majority of issues early I'm happy.

Cheers,
Robert.

**Pull request closed without merging**
