### PR TITLE
Subpass threading with integration of NextSubPass and ExecuteSecondaryCB

### PR DESCRIPTION
**Pull request by mp3butcher**
one commit stand for a bug fix (MT freeze) https://github.com/vsg-dev/VulkanSceneGraph/pull/158/commits/3a73d0d6870572f6f74c5964769da7f45c2c446f that may still affect DataPager 
The bug is present in vsg-dev:subpass_threading and is reproducible by launching lot of instances of the vsgsubpass example (launch 6 instance and swap between windows seems to be a good way to provoke it)

### CODE REVIEW

**Comment by robertosfield** [comment]
Did you mean to generate a PR into alternate_subpass?

**Comment by mp3butcher** [comment]
> one commit stand for a bug fix (MT freeze) [3a73d0d](https://github.com/vsg-dev/VulkanSceneGraph/commit/3a73d0d6870572f6f74c5964769da7f45c2c446f) that may still affect DataPager
> The bug is present in vsg-dev:subpass_threading and is reproducible by launching lot of instances of the vsgsubpass example (launch 6 instance and swap between windows seems to be a good way to provoke it)

indeed...

**Comment by robertosfield** [comment]
The PR changes 22 files, with 34 commits, this makes is really hard to know what is what when trying to compare and understand what you are intending or what problems you have.  It's getting to the point where it's too unwieldy a set of changes to mange.

This kinda highlights the problem with moving ahead of where I'm ready to work on.  The changes are too fundamental to just merge with master with problem review of the issues being tackled.  We have to get these features right.

I don't have any design document and high level guidance on your own thinking on these various elements of work so I have to read what I can from the code and what you to my questions and do my best guess as to what you are thinking and how this relates to the code.  I'm also have to learn about the Vulkan features at the same time.

Put all this together and it's a bit of nightmare to reign things in enough so I can do what is right for the code long term. This is why I've been saying I need to have the clear time to think about stuff myself and why I need you patience for me to catch and put the time in.  

For this PR I'm not sure there is any point in it.  The alternate_subpass branch is a deliberately an alternate implementation, it's not meant to be merged with your own approach.   It's supposed to be there so I can look at different approaches and cherry-pick the bests that will eventually make it into master.

**Comment by mp3butcher** [comment]
I could rebase this refactoring to reduce the number of commits but i don't know which branch to push to:
- subpass branch is unthreaded  with "lego" commands design
- subpass_thread branch is threaded  with "lego" commands design
- this branch is threaded with integrated commands design (no lego commands to play with)
I leave this to your jugement

**Comment by robertosfield** [comment]
The most useful thing right now would be pause and wait for me to review the various branches and learn about the Vulkan features, your implementations and do my own thinking.

**Comment by robertosfield** [comment]
@juval  I have now completed my first iteration of adding multi-threaded record traversals to vsg::Viewer, instigated by calling Viewer::setupThreading() after all the RecordAndSubmitTasks are assigned.  

Note the thread functionality is self contained within Viewer, with only three methods Viewer::setupThreading(), Viewer::stopThreading and Viewer::recordAndSubmit().  The thread setup uses std::thread in combination with a new vsg::FrameBlock and vsg::Barrier class, rather than leverage the general purpose vsg::OperationThreads like you work.  

The reason why this is appropriate is that for best performance you want to assign a thread to a specific cpu core(s) so that core works on the same data each frame keeping it's cache warm, rather than have the tasks of recording floating from core to core.  The vsgmultigpu example illustrates how the created threads affinity can be setup.

Another advantage of handling the threading up at the Viewer class is that it can make decisions about what type of threading to use - which it should be thread per task, or thread per command graph and what combination of these to use if different tasks have different numbers of command graphs.  This approach allows all the tasks and the command recording within them to run fully multi-threaded.  The approach you took was multi-threaded within each task, but each task was done in series.

Another strength of the new approach is that all synchronization objects and the thread setup are all managed within one class and a small set of methods, rather than have synchronization objects being spread across objects.  Having these objects be spread out increases the chances that code changes inadvertently break the design/implementation constraints.

While the direction for viewer level multi-threading is now established (and in master) I haven't attempted to tackle the issue of primary/secondary CommandBuffer and ExecuteCommands.  I am keen to get these fully supported but don't know yet how best to integrate them.  

This branch is obviously a starting point that I'll use as a reference, but it's complicated because it now contains multi-threading work that isn't going to be merged with master.

When I start tackling the secondary CommandBuffer/Graph/ExecuteCommands functionality I will need to create a new branch and cherry-pick what elements are in this branch or in the other subpass branch into it.  I'll need to create an example, or examples to test out the secondary CommandBuffer/Graph/ExecuteCommands functionality and cherry-pick from your subpass branch where appropriate.

I'm happy to take suggestions on what type of functionality that is important to preserve in this process.  It's been a full on week working on multi-threading so I won't attempt to tackle the above work until next week.

**Comment by robertosfield** [comment]
@juval Over the last few days I've been working on secondary CommandBuffer/Graph support and ExecuteCommands.  I've used your subpass branch work as a reference and have leaned a lot about what is required to implement the functionality.  Conceptually the new work is very close to your original implementation, but design/implementation wise differs.  Usage wise it's very close, but with a few small differences that should hopefully make it easier to understand and use.  The work is checked into the ExecuteCommands branches of VSG and vsgExamples:

https://github.com/vsg-dev/VulkanSceneGraph/tree/ExecuteCommands
https://github.com/vsg-dev/vsgExamples/tree/ExecuteCommands

The new implementation isn't yet compatible with mulit-threaded CommandGraph recording, multi-threaded viewer functionality was added separately a few weeks ago, what is missing is the coordination of the recording of the secondaries with the calls to vkCmdExecuteCommands.  

Just getting secondaries working is complex enough (kudos there in beating me to it by several months) so I haven't tried to deal with the multi-threading part in my ExecuteCommands work so far.  Now that I've got the single threaded case working fine I'll move on the multi-threading case.  I'm hoping that use of vsg::Latch should be sufficient, but I'll need to get down and implement stuff to find out what will work or not.  I'm hoping to wrap this all up this weekend.

I hope the new design/implementation will make sense to you, it's main difference is the way that the functionality is encapsulated more tightly within each class, with less dependencies on the specifics of the internal implementation details of other classes.  I'm pretty happy with the end result even if the birth of it hasn't been straight forward.

**Comment by robertosfield** [comment]
@juval I have got the multi-threading work, expanded the vsgexecutecommands example to allow for loading of user defined models, animation paths and doing performance test:

https://github.com/vsg-dev/VulkanSceneGraph/pull/184
https://github.com/vsg-dev/vsgExamples/blob/master/Desktop/vsgexecutecommands/vsgexecutecommands.cpp

I haven't yet implemented the lazy updating of the secondary CommandGraphs, but that should be possible with the new design with a few additions.  I won't tackle this right away as I have a whole load of client work to get back to.

I have merged the ExecuteCommands branches with master of VSG and vsgExamples.  As far as I can tell all the functionality in the various subpass threading branches is now available in the respective master even if design/implementation wise it differs.  For me this provides closure on these previous work so I'll be deleting this branches today. If there are any features missing from VSG master w.r.t subpass and VkExecuteCommands let me know.

**Comment by mp3butcher** [comment]
I haven't taken the time to review your work...notably on threading stuff but i've got my idea here:
Associate commandgraph to their respective PassGraph::SubPass (strong subpass2cg and weak cg2subpas) would allow to schedule  commandbuffer threaded production (using PassGraph to drive scheduler).
A simple schedule policy like:
Parse PassGraph to find independant cg
while (card(parser.found>0)
if(card(parser.found)<numthreadavailable)
try to find new cg to process based on last iteration processed
assign parser.found to available thread
threads.join()
end loop

**Comment by mp3butcher** [comment]
> 
> 
> I haven't taken the time to review your work...notably on threading stuff but i've got my idea here:
> Associate commandgraph to their respective PassGraph::SubPass (strong subpass2cg and weak cg2subpas) would allow to schedule commandbuffer threaded production (using PassGraph to drive scheduler).
> A simple schedule policy like:
> 
> ```
> Parse PassGraph to find independant cgs
> while (card(parser.found>0)
>     if(card(parser.found)<numthreadavailable)
>         try to find new cgs to process based on last iteration processed
>     assign parser.found to available threads
>     threads.join()
> end loop
> ```

scheduling  would allow to get rid of any sync primitives

**Comment by robertosfield** [comment]
I decided not to follow the PassGraph approach, I found it overly complicated and obfuscated the underlying connection to Vulkan.  I went with straight configuration of the RenderPass, it's more long winded to setup but it's got a direct connection to VkRenderPass setup so easier to leverage Vulkan documentation and understanding.

I'm really happy with the threading approach now in master.  I scales better as it works across RecordAndSubmitTask boundaries, and simpler with the synchronization functionality more closely encapsulated to the threading itself.

For me the subpass work was appreciated as a reference but on the design and implementation side a bit more experience helps to produce something a bit cleaner and more flexible.  My hope is that you'll be able to learn from the approach I've taken and be able to gain some insights in how to tackle OO design and threading better.

**Comment by mp3butcher** [comment]
> I think you don't understand the 
> 
> > 
> > 
> > > I haven't taken the time to review your work...notably on threading stuff but i've got my idea here:
> > > Associate commandgraph to their respective PassGraph::SubPass (strong subpass2cg and weak cg2subpas) would allow to schedule commandbuffer threaded production (using PassGraph to drive scheduler).
> > > A simple schedule policy like:
> > > ```
> > > Parse PassGraph to find independant cgs
> > > while (card(parser.found>0)
> > >     if(card(parser.found)<numthreadavailable)
> > >         try to find new cgs to process based on last iteration processed
> > >     assign parser.found to available threads
> > >     threads.join()
> > > end loop
> > > ```
> > 
> > scheduling would allow to get rid of any sync primitives
> 
> I decided not to follow the PassGraph approach, I found it overly complicated and obfuscated the underlying connection to Vulkan. I went with straight configuration of the RenderPass, it's more long winded to setup but it's got a direct connection to VkRenderPass setup so easier to leverage Vulkan documentation and understanding.
> 
> I'm really happy with the threading approach now in master. I scales better as it works across RecordAndSubmitTask boundaries, and simpler with the synchronization functionality more closely encapsulated to the threading itself.
> 
> For me the subpass work was appreciated as a reference but on the design and implementation side a bit more experience helps to produce something a bit cleaner and more flexible. My hope is that you'll be able to learn from the approach I've taken and be able to gain some insights in how to tackle OO design and threading better.

I think you misunderstand the purpose i want to give to PassGraph : 
- I originally used it to simplify renderpass definition, you find obfuscated but it's just a (too inlined?) nodal represenation of the render pass...
- The second usage i came through is to take this graph as a knowledge base in order to schedule commandgraph production: as each cg is given a renderpass and a subpass index one could replace it with a PassGraph::Subpass weak pointer. And storing as the strong ptrs these cg in the supass would give a way to schedule without any synchronization cg (command graph) production operations (through navigation in the passgraph and check if associated cgs are dirties).

... I found potential in this  idea this last weeks, but i'm too busy with the job to code these days...
I'll try to study your threading  implementation on free time...

**Comment by robertosfield** [comment]
On Mon, 25 May 2020 at 17:48, Julien Valentin <notifications@github.com>
wrote:

> I think you misunderstand the purpose i want to give to PassGraph :
>
>    - I originally used it to simplify renderpass definition, you find
>    obfuscated but it's just a (too inlined?) nodal represenation of the render
>    pass...
>    - The second usage i came through is to take this graph as a knowledge
>    base in order to schedule commandgraph production: as each cg is given a
>    renderpass and a subpass index one could replace it with a
>    PassGraph::Subpass weak pointer. And storing as the strong ptrs these cg in
>    the supass would give a way to schedule without any synchronization cg
>    (command graph) production operations (through navigation in the passgraph
>    and check if associated cgs are dirties).
>
>
I am really experienced at trying to review 3rd party code and trying to
make sense of it.  It's been a big part of my job for the last 20 years.  I
struggled to make sense of why all this extra complexity.  If I struggled
with it then for sure other people coming down the line will be left
confused about all these interconnecting classes where the only role was to
fill in the RenderPassCreateInfo structure.  With the OSG project I was
left with code that is overly complicated and different to understand and
really hard to explain to others and maintain.

For the VSG project to succeed I can't allow it follow this same mistake.
Code that makes it into the VSG need to justify it's existence, it needs to
minimal and complete and totally focused on what it does.  Code that meets
this requirement is hard to write.  Can take several goes to get it right.
Good code looks trivial when you read it, it looks obvious how it works.
This type of code is the hardest to write.

>
>
> ... I found potential in this idea this last weeks, but i'm too busy with
> the job to code these days...
> I'll try to study your threading implementation on free time...
>
It's some of my best threading work so I'd recommend it.  It's far better
than anything in the OSG.

**Pull request closed without merging**
