### PR TITLE
win32 compile errors

### PR DESCRIPTION
**Pull request by LaurensVoerman**
# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes Compile error on Win32
Trying to get things running I found a few problems on win32, and to avoid dupicate work I would like to submit my fixes for merging. As I don't have an executable build yet, nothing is tested.

Regards, Laurens.
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Not tested

**Test Configuration**:
* OS: Win 10 1803 x64
* Hardware: i7 6700K / 32BG / GeForce 1080 417.22
* Toolchain: Visual Studio Community 2017
* SDK:

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by tomhog** [comment]
So in my Win32Events branch I am for now retrieving the window class name for the HWND window handle itself. This might be another reason to store the traits in the window

**Comment by vsg-dev** [comment]
@tomhog, how close are you to getting your Win32Events branch in a state that it can be merged with master?

I can add a Traits object to Window, I'm inclined to go with making Traits something created on the heap, then we can subclass from Traits and extend it if really necessary.  Let me know what will help at your end.

**Comment by tomhog** [comment]
@vsg-dev Yeah making traits something we can extend is looking more and more appealing. Then we can have a few platform specific bits. There are things like orientations on mobile devices that people may or may not care about.

win32-events is good to merge now. I'm just doing a rebuild after pulling in the latest master stuff

**Comment by vsg-dev** [comment]
@LaurensVoerman, I have just merged @tomhog's Win32 event changes that should address the error you've seen so will close this PR.

**Pull request closed without merging**
