### PR TITLE
Needed changes for cubemap support

### PR DESCRIPTION
**Pull request by anormann1974**
Hi Robert,

in this pull request you will find the needed changes in vsg to support cubemaps. I have created a new class ArrayCube to store the image data. Currently only uncompressed formats are supported. A pull request for compressed data will follow later.

I also merged vsg master branch into the ReadStream branch to be up to date.

### CODE REVIEW

**Comment by robertosfield** [comment]
Thanks Norman.  Just done a first pass review.  So that I could see the key differences I've merged master into the vsg-dev/VulkanSceneGraph ReadStream.  I now just see the 8 files changed.

Originally I had assumed we could reuse Array3D as the basis for doing cubemaps.  I see that there are differences in how data is passed to Vulkan that require different treatment with setting up of Layers rather than depth.  I'm now wondering if a Texture2DArray equivalent will need the same treatment.

I will need to do another pass over looking in detail at the changes before setting upon a path.  Currently I'm inclined towards merging this branch with with vsg-dev/VulkanScenerGraph/ReadStream and doing a code review in situ.  I'm also still curious about the path reuse Array3D for doing cubemaps and texture 2d arrays so may create a parallel branch and see how it all just hangs together, then chose which ever implementation feels the more natural to use.

**Comment by anormann1974** [comment]
I also tried to reuse Array3D, but I got some troubles. That was the reason why I create the ArrayCube class. One other solution might be to use Array2D and add an array member for handling faces.

...
 uint32_t m_width; 
uint32_t m_height; 
uint32_t m_faces;
...

Then the ArrayCube class will bee obsolete.

**Comment by robertosfield** [comment]
Hi Andre,

On Fri, 29 Jan 2021 at 09:26, Andre Normann <notifications@github.com>
wrote:

> I also tried to reuse Array3D, but I got some troubles.
>
What problems did you come across?


> That was the reason why I create the ArrayCube class. One other solution
> might be to use Array2D and add an array member for handling faces.
>

I find the name ArrayCube a bit awkward.  Perhaps it'd be OK just to use
Cubemap.

> ...
> uint32_t m_width;
> uint32_t m_height;
> uint32_t m_faces;
>
That's a novel approach.  It would mean users of Array2D would need to
check for faces to make sure they process it correctly.

I've merged and will review those changes.  I will do a eview.  I am also
working on a new vsgGIS lib today so will have to juggle my time between
these tasks.

**Comment by anormann1974** [comment]
> On Fri, 29 Jan 2021 at 09:26, Andre Normann ***@***.***> wrote: I also tried to reuse Array3D, but I got some troubles.
> What problems did you come across?

Computing mipmap size was one problem. I stored the num of arrays (for cubemaps always 6) inside the depth component of vsg::Array3D. But this will be taken into mipmap calculation. In vsg::Image the imageType is set to VK_IMAGE_TYPE_3D, but for cubemap it must be VK_IMAGE_TYPE_2D. This can be handled by the use application, but it would be nice to have it set automatically. 

-André

**Comment by anormann1974** [comment]
> That's a novel approach. It would mean users of Array2D would need to check for faces to make sure they process it correctly. I've merged and will review those changes. I will do a eview. I am also working on a new vsgGIS lib today so will have to juggle my time between these tasks.

vsgGIS is very interesting. I work for an engineering office and have developed an OSG based program with GIS/CAD functionality. It is used for very large terrain visualization, which can embed GIS and CAD data as well. So any information about vsgGIS is welcome :-). Maybe best via email.

-André

**Pull request merged**
