### PR TITLE
Add class template link test case

### PR DESCRIPTION
**Pull request by rhabacker**
## Description
Add test case for linking class templates on various platforms, see https://github.com/vsg-dev/vsgGIS/issues/13

### CODE REVIEW

**Comment by robertosfield** [comment]
As an experiment I've checked in this PR as a branch called rhabacker-AddClassTemplateLinkTestCase.  I've also just pushed the addition of the exports to see what the effect is on the test build under Windows.

**Comment by robertosfield** [comment]
@rhabacker I've just merged a vsgExamples PR from @sbrkopac that adds automated build of both the VSG and vsgExamples together, and while there are 48 warnings (mostly float conversions) there isn't any build failures.  The examples do use vsg::Array etc.  This is the result from the DLL build:

[vsgExamples automated build](https://github.com/vsg-dev/vsgExamples/runs/3578797065)

Which is curious, I would have expected the same errors as in your test case.  Could this be an indication that the test case isn't correctly linking to the lib?

**Comment by rhabacker** [comment]
> I would have expected the same errors as in your test case.

Did that build with gdal ? The mentioned error happens on linking symbols required by gdal_utils.cpp.

**Comment by sbrkopac** [comment]
> > I would have expected the same errors as in your test case.
> 
> Did that build with gdal ? The mentioned error happens on linking symbols required by gdal_utils.cpp.

I have opened a [draft PR](https://github.com/vsg-dev/vsgGIS/pull/14) in vsgGIS to enable CI builds. Please ignore the macos error as I haven't finished that up yet.

You can see the error on [this run](https://github.com/sbrkopac/vsgGIS/runs/3579628412). @robertosfield sorry for any confusion regarding the naming of the CI tests.

**Comment by robertosfield** [comment]
By removing the export for the Value and Array classes and adding the 

#include <vsg/core/Visitor.h>
#include <vsg/core/ConstVisitor.h>

To the test-linking-class-templates.cpp the Windows DLL now builds cleanly, check the top item out, where the build was finally fixed.
[
https://github.com/vsg-dev/VulkanSceneGraph/commits/rhabacker-AddClassTemplateLinkTestCase](
https://github.com/vsg-dev/VulkanSceneGraph/commits/rhabacker-AddClassTemplateLinkTestCase)

**Comment by robertosfield** [comment]
I modified the test adding the include <vsg/core/ConstVisitor.h> and include <vsg/core/Visitor.h> and it compiles without errors.  No need for any exports in Value/Array, and if one does add them then it breaks the Windows DLL build.

**Comment by rhabacker** [comment]
> and adding the
> #include <vsg/core/Visitor.h>
> #include <vsg/core/ConstVisitor.h>

That means any client code which want to use templates must include that header files ?

**Pull request closed without merging**
